train:
  batch_size: 128
  epochs: 10
  log_interval: 10
  lr: 0.001
  loss_function: "VAE"
  shuffle: True

model:
  type: "VAE"
  embedding_size: 32
  output_size: 512

logger:
  results_path: "results/"
  checkpoint_path: "checkpoints/"
  enable_wandb: True

system:
  cuda: True
  seed: 42

dataset:
  name: "MNIST"

run_date: ${now:%Y_%m_%d_%H_%M}
