train:
  batch_size: 32
  epochs: 10
  log_interval: 50
  lr: 1e-4
  loss_function: "VAE"
  shuffle: True

model:
  type: "VAE"
  embedding_size: 64
  output_size: 512

results_path: "results/"
checkpoint_path: "checkpoints/"

system:
  device: "cuda:0"
  seed: 42

dataset:
  name: "MNIST"

run_date: ${now:%Y_%m_%d_%H_%M}
run_name: ${model.type}-${dataset.name}-${now:%Y-%m-%d-%H-%M}
