train:
  batch_size: 128
  epochs: 10
  log_interval: 10
  lr: 0.001
  loss_function: "MSE"
  shuffle: True

model:
  type: "AE"
  embedding_size: 32

logger:
  results_path: "results/"
  checkpoint_path: "checkpoints/"
  enable_wandb: False

system:
  cuda: True
  seed: 42

dataset:
  name: "MNIST"

vqvae:
    in_channels: 3,
    num_hiddens: 128,
    num_downsampling_layers: 2,
    num_residual_layers: 2,
    num_residual_hiddens: 32,
    embedding_dim: 64,
    num_embeddings: 512,
    use_ema: use_ema,
    decay: 0.99,
    epsilon: 1e-5,

run_date: ${now:%Y_%m_%d_%H_%M}
